#figureS3.R
## Generate plots for S3B, SDevo results for strict clock (diversified tumor sims)

library(tidyverse)

#Get true differences
true_diff_df <- read_csv("../eden/stats/validation_growth_and_death_rates_weighted.csv") %>% 
    dplyr::mutate(true_birth_rate_diff_weighted=mean_edge_birth_rate-mean_center_birth_rate)

# Posterior summary statistics for all sdevo analyses of simulated tumors are 
# generated by run_beast_to_ess.sh and compile_posterior_summaries.sh
all_posteriors_summary_df <- read_tsv("../eden/stats/posteriors/posterior_summary_all.tsv") %>% 
    left_join(., true_diff_df, by = "dr")

birth_rate_strict_clock_fig <- all_posteriors_summary_df %>% 
    filter(minBirthRateESS > 200, n >= 50, clock_model == "strict") %>% 
    mutate(dr = as.numeric(dr)) %>%
    ggplot(aes(x=true_birth_rate_diff_weighted, y=mean_birth_rate_diff), color = "black") +
    geom_point(color = "black") +
    theme_classic() +
    geom_abline(slope=1, intercept = 0, linetype = "dashed", color = "black") +
    geom_errorbar(aes(ymin = birthRate_hdi95_lower, ymax = birthRate_hdi95_upper), color = "black", alpha = 0.8) +
    xlab("True birth rate difference (edge - center)") +
    ylab("Estimated birth rate difference (edge - center)") +
    theme(text = element_text(size = 15)) +
    facet_wrap(~n)
birth_rate_strict_clock_fig
ggsave(file = "../figures/birth_rate_strict_clock_fig.png", birth_rate_strict_clock_fig, height = 6, width = 9)    
