#figureS4.R

##Scripts to make figure S4

library(tidyverse)
library(tumortree)


#example random sampling diagram
## Local directories
### Use to create more minimal dataset for 
# example_cells <- read_csv("/Volumes/BALAENA/projects/spatial_tumor_growth_simulation/outputs/raw_simulation_results/validation/cells_death_rate_validation_pop_500_dr_0.27.csv") %>%
#      tumortree::filter_alive_cells()
# 
# 
# example_cells <- mark_boundary(cells_to_mark = example_cells, alive_cells = example_cells)

#Write example tumor to CSV
#write_csv(example_cells, "../eden/simulation_data/alive_cells_death_rate_validation_pop_1000_dr_0.27.csv")

#To skip to visualization
example_cells <- read_csv(file = "../eden/simulation_data/alive_cells_death_rate_validation_pop_1000_dr_0.27.csv")

set.seed(392)
example_cells_diversified <- example_cells %>% 
    tumortree::sample_alive_cells(., n =50, diversified_sampling = TRUE) %>% 
    dplyr::filter(sampled)

example_cells_random <- example_cells %>% 
    tumortree::sample_alive_cells(., n =50, diversified_sampling = FALSE) %>% 
    dplyr::filter(sampled)

colors_edge_center <- get_color_palette(names = c("edge", "center"))

example_tumor_inset_diversified <- ggplot(example_cells, aes(locx, locy, color = ifelse(est_edge == 1, "edge", "center"))) +
    geom_point() + theme_void() +
    #geom_point(data = example_cells_diversified, shape = 21, aes(fill = ifelse(est_edge == 1, "edge", "center")), color = "black", size =3)+
    geom_point(data = example_cells_diversified, shape = 1, fill = "black",  color = "black", alpha = 1, size = 3)+
    scale_fill_manual(values = colors_edge_center) +
    scale_color_manual(values = colors_edge_center) +
    theme(legend.position = "none") 

example_tumor_inset_diversified
ggsave(file = "../figures/diversified_sampling_example_tumor.png", example_tumor_inset_diversified, height = 5, width = 5)    


example_tumor_inset_random <- ggplot(example_cells, aes(locx, locy, color = ifelse(est_edge == 1, "edge", "center"))) +
    geom_point() + theme_void() +
    #geom_point(data = example_cells_diversified, shape = 21, aes(fill = ifelse(est_edge == 1, "edge", "center")), color = "black", size =3)+
    geom_point(data = example_cells_random, shape = 1, fill = "black",  color = "black", alpha = 1, size = 3)+
    scale_fill_manual(values = colors_edge_center) +
    scale_color_manual(values = colors_edge_center) +
    theme(legend.position = "none") 

example_tumor_inset_random
ggsave(file = "../figures/random_sampling_example_tumor.png", example_tumor_inset_random, height = 5, width = 5)    

######### Sampling and clock model comparison (posteriors) ###########

#Read in true differences
#From extract_validation_sims_rates.R
true_diff_df <- read_csv("../eden/stats/validation_growth_and_death_rates_weighted.csv") %>% 
    dplyr::mutate(true_birth_rate_diff_weighted=mean_edge_birth_rate-mean_center_birth_rate)

# Posterior summary statistics for all sdevo analyses of simulated tumors are 
# generated by run_beast_to_ess.sh and compile_posterior_summaries.sh
all_posteriors_summary_df <- read_tsv("../eden/stats/posteriors/posterior_summary_all.tsv") %>% 
    left_join(., true_diff_df, by = "dr")

clock_comparison_growth_rate_posteriors_df <- all_posteriors_summary_df  %>% 
    dplyr::mutate(clock_model = factor(clock_model, levels = c('strict', 'state_dependent'))) %>% 
    dplyr::arrange(clock_model)


clock_comparison_growth_rate_posteriors_df_subset <- clock_comparison_growth_rate_posteriors_df %>% 
    dplyr::filter(n==100, minBirthRateESS > 200)

clock_colors <- c("state_dependent" = "#3A5A40", "strict" = "#ECA966")

facet_labels <- c("strict" = "Strict",
                  "state_dependent" = "State-dependent", 
                  "diversified" = "Diversified", 
                  "random" = "Random")

facet_labeller <- function(variable,value){
    return(facet_labels[value])
}

clock_rate_comparison_posteriors_plot <- clock_comparison_growth_rate_posteriors_df_subset %>% 
    ggplot(., aes(x=true_birth_rate_diff_weighted, y=mean_birth_rate_diff, color = clock_model)) +
    geom_point(aes(color = clock_model)) +
    theme_bw() +
    facet_grid(rows = vars(sampling), cols = vars(clock_model), labeller = facet_labeller) +
    geom_abline(slope=1, intercept = 0, linetype = "dashed", color = "black") +
    geom_errorbar(aes(ymin = birthRate_hdi95_lower, ymax = birthRate_hdi95_upper, color=clock_model), alpha = 0.6, size = 1) +
    xlab("True birth rate difference (edge - center)") +
    ylab("Estimated birth rate difference (edge - center)") +
    scale_color_manual(values = clock_colors) +
    theme(legend.position = "none") +
    theme(text=element_text(size = 15))
clock_rate_comparison_posteriors_plot
ggsave(file = "../figures/clock_rate_comparison_birth_rate_posteriors.png",
       clock_rate_comparison_posteriors_plot, height = 6, width = 6)


