#summarize_physicell_state_clocks_runs.R

## Script to summarize marginal posterior distributions of parameter estimates for physicell runs

## Output used for plots in figure 4 (generated by figure4.R)

library(tumortree)
library(tidyverse)
library(HDInterval)
library(coda)


calculate_growth_rate_posterior <- function(mcmc_log, log_file,
                                            true_growth_rate_differences_dir = "",
                                            original_sample_size = "100", 
                                            input_b = 0.00460405156537753) {
    
    print(log_file)
    if (is.null(log_file)) {
        
        return(NA)
    }
    #calculate effective sample size
    
    ess <- try(coda::effectiveSize(mcmc_log))
    if (! is.numeric(ess)) {
        ess <- 0
    }


    
    #extract simulation info from filename
    dr_extract <- regmatches(basename(log_file),
                            gregexpr("(?<=d)[[:digit:]]+.*?(?=_)", basename(log_file), perl = TRUE))[[1]]
    
    i_extract <- regmatches(basename(log_file),
                             gregexpr("(?<=i)[[:digit:]]", basename(log_file), perl = TRUE))[[1]]
    
    n_extract <- regmatches(basename(log_file),
                             gregexpr("(?<=n_)[[:digit:]]+", basename(log_file), perl = TRUE))[[1]]
    
    single_death <- any(grepl("single_death", log_file, fixed = TRUE))
    
    id_extract <- regmatches(basename(log_file),
                             gregexpr("(?<=_s)[[:digit:]]+", basename(log_file), perl = TRUE))[[1]]
    
    if (length(n_extract) == 0) {
        n_extract <- original_sample_size
    }
    
    #get true growth rate differences
    true_growth_rate_differences_file <- paste0(true_growth_rate_differences_dir, "/", gsub("_diversified_m1_n100", "",
                                                                                            gsub("_single_death", "", 
                                                                                            gsub("_n_[0-9]+", "",
                                                                                                 gsub(".log", "", basename(log_file), perl = TRUE), perl = TRUE))), ".tsv", sep = "")
    true_growth_rate_differences_df <- read_tsv(true_growth_rate_differences_file) %>%
        group_by(edgeAssociated) %>%
        dplyr::summarize(mean_growth_rate = weighted.mean(avGrowth, n))
    
    #death rate is fixed proportion of input birth
    true_death <- as.numeric(dr_extract) * input_b
    
    #birth rates are recorded during simulations because they also depend on spatial pressure restrictions
    true_edge_birth <- true_growth_rate_differences_df$mean_growth_rate[true_growth_rate_differences_df$edgeAssociated][[1]]
    true_edge_growth <- true_edge_birth - true_death
    
    true_center_birth <- true_growth_rate_differences_df$mean_growth_rate[! true_growth_rate_differences_df$edgeAssociated][[1]]
    true_center_growth <- true_center_birth - true_death
    
    
    #relative edge/center calculations
    true_birth_rate_difference = true_edge_birth -  true_center_birth
    true_birth_rate_ratio = true_edge_birth / true_center_birth
    
    true_growth_rate_difference = true_edge_growth -  true_center_growth
    true_growth_rate_ratio = true_edge_growth / true_center_growth
    
    #estimates from mcmc logs
    birthRate_loc0_posteriors <- mcmc_log[,"birthRateCanonical.0"]
    birthRate_loc1_posteriors <- mcmc_log[,"birthRateCanonical.1"]
    
    birthRateDiff_posteriors <- birthRate_loc1_posteriors - birthRate_loc0_posteriors
    birthRateRatio_posteriors <- (birthRate_loc1_posteriors/birthRate_loc0_posteriors)
    
    if (single_death) {
        
        loc0_posteriors <- mcmc_log[,"birthRateCanonical.0"] -  mcmc_log[,"deathRateCanonical"]
        loc1_posteriors <- mcmc_log[,"birthRateCanonical.1"] -  mcmc_log[,"deathRateCanonical"]
        
    } else {
        
        loc0_posteriors <- mcmc_log[,"birthRateCanonical.0"] -  mcmc_log[,"deathRateCanonical.0"]
        loc1_posteriors <- mcmc_log[,"birthRateCanonical.1"] -  mcmc_log[,"deathRateCanonical.1"]
    }
    
    
        
    growthRateDiff_posteriors <- loc1_posteriors - loc0_posteriors
    growthRateRatio_posteriors <- (loc1_posteriors/loc0_posteriors)

    posterior_df <-  data.frame("mean_growth_rate_diff" = mean(growthRateDiff_posteriors),
                                "median_growth_rate_diff" = median(growthRateDiff_posteriors),
                                "mean_growth_rate_ratio" = mean(growthRateRatio_posteriors),
                                "median_growth_rate_ratio" = median(growthRateRatio_posteriors),
                                "mean_birth_rate_diff" = mean(birthRateDiff_posteriors),
                                "median_birth_rate_diff" = median(birthRateDiff_posteriors),
                                "mean_birth_rate_ratio" = mean(birthRateRatio_posteriors),
                                "median_birth_rate_ratio" = median(birthRateRatio_posteriors),
                                "true_edge_growth_rate" = true_edge_growth, 
                                "true_center_growth_rate" = true_center_growth, 
                                "true_growth_rate_diff" = true_growth_rate_difference, 
                                "true_growth_rate_ratio" = true_growth_rate_ratio, 
                                "true_edge_birth_rate" = true_edge_birth, 
                                "true_center_growth_rate" = true_center_birth, 
                                "true_birth_rate_diff" = true_birth_rate_difference, 
                                "true_birth_rate_ratio" = true_birth_rate_ratio, 
                                "growthRate_hdi95_lower" = hdi(growthRateDiff_posteriors,  credMass = 0.95)[1],
                                "growthRate_hdi95_upper" = hdi(growthRateDiff_posteriors,  credMass = 0.95)[2],
                                "growthRate_hdi85_lower" = hdi(growthRateDiff_posteriors,  credMass = 0.85)[1],
                                "growthRate_hdi85_upper" = hdi(growthRateDiff_posteriors,  credMass = 0.85)[2],
                                "growthRate_hdi75_lower" = hdi(growthRateDiff_posteriors, credMass = 0.75)[1],
                                "growthRate_hdi75_upper" = hdi(growthRateDiff_posteriors,  credMass = 0.75)[2],
                                "birthRate_hdi95_lower" = hdi(birthRateDiff_posteriors,  credMass = 0.95)[1],
                                "birthRate_hdi95_upper" = hdi(birthRateDiff_posteriors,  credMass = 0.95)[2],
                                "birthRate_hdi85_lower" = hdi(birthRateDiff_posteriors,  credMass = 0.85)[1],
                                "birthRate_hdi85_upper" = hdi(birthRateDiff_posteriors,  credMass = 0.85)[2],
                                "birthRate_hdi75_lower" = hdi(birthRateDiff_posteriors, credMass = 0.75)[1],
                                "birthRate_hdi75_upper" = hdi(birthRateDiff_posteriors,  credMass = 0.75)[2],
                                "dr" = dr_extract,
                                "i" = i_extract,
                                "n" = n_extract,
                                "id" = id_extract,
                                "minBirthRateESS" = min(ess["birthRateCanonical.1"], ess["birthRateCanonical.0"]),
                                "single_death" = single_death)
    
    
    return(posterior_df)
    
    
}

# Record of local directory
# log_files_2D_neut_bdg <-  list.files(path = "/Volumes/BALAENA/projects/spatial_tumor_growth_simulation/outputs/beast_analysis/state_dependent_clock_model/validation/physicell/logs/2D_neut_bdg/diversified_100",
#                                      pattern = "sampconfig_m0")
#logs_2D_neut_bdg <- readRDS("/Volumes/BALAENA/projects/spatial_tumor_growth_simulation/outputs/beast_analysis/state_dependent_clock_model/validation/physicell/logs/2D_neut_bdg/diversified_100/all_mcmc_logs.rds")

log_files_2D_neut_bdg <-  list.files(path = "../physicell/logs/2D_neut_bdg/diversified_100",
                                     pattern = "sampconfig_m0")
logs_logs_2D_neut_bdg <- purrr::map(log_files_2D_neut_bdg, readLog)


# 2D boundary-driven growth (with selection)
logs_2D_sel_bdg <- read_mcmc_logs(path = "../physicell/logs/2D_sel_bdg_highermu/diversified_100",
                              pattern = "[0-9][0-9][0-9].log", burnin = 0.2, different_lengths = TRUE)

# logs_2D_sel_bdg <- read_mcmc_logs(path = "/Volumes/BALAENA/projects/spatial_tumor_growth_simulation/outputs/beast_analysis/state_dependent_clock_model/validation/physicell/logs/2D_sel_bdg_highermu/diversified_100",
#                               pattern = "[0-9][0-9][0-9].log", burnin = 0.2, different_lengths = TRUE)
#

#saveRDS(logs_2D_sel_bdg, file = "/Volumes/BALAENA/projects/spatial_tumor_growth_simulation/outputs/beast_analysis/state_dependent_clock_model/validation/physicell/logs/2D_sel_bdg_highermu/diversified_100/all_mcmc_logs.rds")
#logs_2D_sel_bdg <- readRDS("/Volumes/BALAENA/projects/spatial_tumor_growth_simulation/outputs/beast_analysis/state_dependent_clock_model/validation/physicell/logs/2D_sel_bdg_highermu/diversified_100/all_mcmc_logs.rds")

# 3D boundary-driven growth (neutral)
logs_3D_neut_bdg <- read_mcmc_logs(path = "../physicell/logs/3D_neut_bdg/diversified_100",
                                   pattern = "[0-9][0-9][0-9].log", burnin = 0.2, different_lengths = TRUE)


#saveRDS(logs_3D_neut_bdg, file = "/Volumes/BALAENA/projects/spatial_tumor_growth_simulation/outputs/beast_analysis/state_dependent_clock_model/validation/physicell/logs/3D_neut_bdg/diversified_100/all_mcmc_logs.rds")
#logs_3D_neut_bdg <- readRDS("/Volumes/BALAENA/projects/spatial_tumor_growth_simulation/outputs/beast_analysis/state_dependent_clock_model/validation/physicell/logs/3D_neut_bdg/diversified_100/all_mcmc_logs.rds")

#Get file names to compile summary dataframe 
log_files_2D_neut_bdg <- list.files(path = "/Volumes/BALAENA/projects/spatial_tumor_growth_simulation/outputs/beast_analysis/state_dependent_clock_model/validation/physicell/logs/2D_neut_bdg/diversified_100",pattern = "sampconfig_m0.*n_.*")

#true_growth_rate_differences_dir_2D_neut_bdg = "/Volumes/BALAENA/projects/spatial_tumor_growth_simulation/outputs/beast_analysis/state_dependent_clock_model/validation/physicell/simulated_data/2D_neut_bdg/diversified_100/growth_rate_differences_new"
true_growth_rate_differences_dir_2D_neut_bdg = "../physicell/simulation_data/2D_neut_bdg/diversified_100/growth_rate_differences_new"


# logs_2D_sel_bdg <- read_mcmc_logs(path = "/Volumes/BALAENA/projects/spatial_tumor_growth_simulation/outputs/beast_analysis/state_dependent_clock_model/validation/physicell/logs/2D_sel_bdg/diversified_100",
#                               pattern = "sampconfig_m0", burnin = 0.2)
# 
log_files_2D_sel_bdg <- list.files(path = "/Volumes/BALAENA/projects/spatial_tumor_growth_simulation/outputs/beast_analysis/state_dependent_clock_model/validation/physicell/logs/2D_sel_bdg_highermu/diversified_100",
                               pattern = "sampconfig_m0")

true_growth_rate_differences_dir_2D_sel_bdg = "/Volumes/BALAENA/projects/spatial_tumor_growth_simulation/outputs/beast_analysis/state_dependent_clock_model/validation/physicell/simulated_data/2D_sel_bdg_highermu/diversified_100/growth_rate_differences_updated"

# logs_3D_neut_bdg <- read_mcmc_logs(path = "/Volumes/BALAENA/projects/spatial_tumor_growth_simulation/outputs/beast_analysis/state_dependent_clock_model/validation/physicell/logs/3D_neut_bdg/diversified_100",
#                                   pattern = "sampconfig_m0", burnin = 0.2)
log_files_3D_neut_bdg <- list.files(path = "/Volumes/BALAENA/projects/spatial_tumor_growth_simulation/outputs/beast_analysis/state_dependent_clock_model/validation/physicell/logs/3D_neut_bdg/diversified_100",
                                   pattern = "sampconfig_m0")

true_growth_rate_differences_dir_3D_neut_bdg = "/Volumes/BALAENA/projects/spatial_tumor_growth_simulation/outputs/beast_analysis/state_dependent_clock_model/validation/physicell/simulated_data/3D_neut_bdg/diversified_100/growth_rate_differences_new"

log_files_2D_neut_bdg <- list.files(path = "/Volumes/BALAENA/projects/spatial_tumor_growth_simulation/outputs/beast_analysis/state_dependent_clock_model/validation/physicell/logs/2D_neut_bdg/diversified_100",pattern = "sampconfig_m0.*n_.*")

growth_rate_posteriors_2D_neut_bdg <- purrr::map2(logs_2D_neut_bdg$logs, logs_2D_neut_bdg$files, 
                                      function(l, f) calculate_growth_rate_posterior(mcmc_log = l,
                                                                                          log_file = f,
                                                                                          true_growth_rate_differences_dir = true_growth_rate_differences_dir_2D_neut_bdg))
growth_rate_posteriors_2D_neut_bdg_df <- growth_rate_posteriors_2D_neut_bdg[! is.na(growth_rate_posteriors_2D_neut_bdg)] %>% 
    bind_rows

write_csv(growth_rate_posteriors_2D_neut_bdg_df, file = "../physicell/stats/growth_rate_posteriors_2D_neut_bdg_n100.csv")



growth_rate_posteriors_2D_sel_bdg <- purrr::map2(logs_2D_sel_bdg$logs, logs_2D_sel_bdg$files, 
                                                  function(l, f) calculate_growth_rate_posterior(mcmc_log = unlist(l),
                                                                                                 log_file = f,
                                                                                                 true_growth_rate_differences_dir = true_growth_rate_differences_dir_2D_sel_bdg))
growth_rate_posteriors_2D_sel_bdg_df <- growth_rate_posteriors_2D_sel_bdg[! is.na(growth_rate_posteriors_2D_sel_bdg)] %>% 
    bind_rows


growth_rate_posteriors_3D_neut_bdg <- purrr::map2(logs_3D_neut_bdg$logs, logs_3D_neut_bdg$files, 
                                                  function(l, f) calculate_growth_rate_posterior(mcmc_log = l,
                                                                                                 log_file = f,
                                                                                                 true_growth_rate_differences_dir = true_growth_rate_differences_dir_3D_neut_bdg))
growth_rate_posteriors_3D_neut_bdg_df <- growth_rate_posteriors_3D_neut_bdg[! is.na(growth_rate_posteriors_3D_neut_bdg)] %>% 
    bind_rows
    
write_csv(growth_rate_posteriors_3D_neut_bdg_df, file = "../physicell/stats/growth_rate_posteriors_3D_neut_bdg_n100.csv")



write_csv(growth_rate_posteriors_2D_sel_bdg_df, file = "../physicell/stats/growth_rate_posteriors_2D_sel_bdg_n100.csv")

